# Generated by Django 4.2.7 on 2025-12-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low', 'Low Stock'), ('out', 'Out of Stock'), ('low-high-demand', 'Low Stock - High Demand')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'stock_alerts',
                'indexes': [models.Index(fields=['product'], name='stock_alert_product_6816f8_idx'), models.Index(fields=['is_read'], name='stock_alert_is_read_af0dfb_idx')],
            },
        ),
    ]
