# Generated by Django 4.2.7 on 2026-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
