# Generated by Django 4.2.7 on 2026-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
