# Generated by Django 4.2.7 on 2025-12-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_sold', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('sale_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'sales_analytics',
                'indexes': [models.Index(fields=['product'], name='sales_analy_product_82c514_idx'), models.Index(fields=['sale_date'], name='sales_analy_sale_da_2be818_idx'), models.Index(fields=['sale_timestamp'], name='sales_analy_sale_ti_c8c9e2_idx')],
            },
        ),
    ]
