# Generated by Django 4.2.7 on 2026-05-13 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='image_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
